#------------------------------------------------------------------------------#
name: Example
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - '.github/workflows/example.yaml*'
      - 'ncbimeta/*'
      - 'test/*'
      - 'requirements.txt'
      - 'setup.py'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
#------------------------------------------------------------------------------#
  example:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, "3.10.1"]
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip Install
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Quick Start Example
        run: |
          NCBImeta --flat --config test/test.yaml --force-pause-seconds 0 --email ${{ secrets.NCBI_EMAIL }} --api ${{ secrets.NCBI_API_KEY }}
          NCBImetaAnnotate --database test/test.sqlite --annotfile test/test_annot.txt --table BioSample
          NCBImetaAnnotate --database test/test.sqlite --annotfile test/test_annot.txt --table BioSample --concatenate
          NCBImetaJoin --database test/test.sqlite --anchor BioSample --accessory "BioProject Assembly SRA Nucleotide" --final Master --unique "BioSampleAccession BioSampleAccessionSecondary BioSampleBioProjectAccession"
          NCBImetaExport --database test/test.sqlite --outputdir test/
