#------------------------------------------------------------------------------#
name: Example
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - '.github/workflows/example.yaml*'
      - 'ncbimeta/*'
      - 'test/*'
      - 'requirements.txt'
      - 'setup.py'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #------------------------------------------------------------------------------#
  # Source Example
  source_example:
    name: Source Example
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, "3.10.1"]
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip Install
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Quick Start Example
        run: |
          NCBImeta --flat --config test/test.yaml --force-pause-seconds 0 --email ${{ secrets.NCBI_EMAIL }} --api ${{ secrets.NCBI_API_KEY }}
          NCBImetaAnnotate --database test/test.sqlite --annotfile test/test_annot.txt --table BioSample
          NCBImetaAnnotate --database test/test.sqlite --annotfile test/test_annot.txt --table BioSample --concatenate
          NCBImetaJoin --database test/test.sqlite --anchor BioSample --accessory "BioProject Assembly SRA Nucleotide" --final Master --unique "BioSampleAccession BioSampleAccessionSecondary BioSampleBioProjectAccession"
          NCBImetaExport --database test/test.sqlite --outputdir test/

  #----------------------------------------------------------------------------#
  # PyPI Example
  pypi_example:
    name: PyPI Example
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Remove the .py after v0.8.0
      - name: Install from PyPI
        run: |
          pip install ncbimeta
          NCBImeta --version

      - name: Quick Start Example
        run: |
          NCBImeta --flat --config test/test.yaml --force-pause-seconds 0 --email ${{ secrets.NCBI_EMAIL }} --api ${{ secrets.NCBI_API_KEY }}
          NCBImetaAnnotate --database test/test.sqlite --annotfile test/test_annot.txt --table BioSample
          NCBImetaAnnotate --database test/test.sqlite --annotfile test/test_annot.txt --table BioSample --concatenate
          NCBImetaJoin --database test/test.sqlite --anchor BioSample --accessory "BioProject Assembly SRA Nucleotide" --final Master --unique "BioSampleAccession BioSampleAccessionSecondary BioSampleBioProjectAccession"
          NCBImetaExport --database test/test.sqlite --outputdir test/

  #----------------------------------------------------------------------------#
  # Conda Example
  conda_example:
    name: Conda Example
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, "3.10.1"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Conda
        uses:  conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge

      - name: Install From Conda
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge -c bioconda ncbimeta
          NCBImeta --version

      - name: Quick Start Example
        shell: bash -l {0}
        run: |
          conda activate ncbimeta
          NCBImeta --flat --config test/test.yaml --force-pause-seconds 0 --email ${{ secrets.NCBI_EMAIL }} --api ${{ secrets.NCBI_API_KEY }}
          NCBImetaAnnotate --database test/test.sqlite --annotfile test/test_annot.txt --table BioSample
          NCBImetaAnnotate --database test/test.sqlite --annotfile test/test_annot.txt --table BioSample --concatenate
          NCBImetaJoin --database test/test.sqlite --anchor BioSample --accessory "BioProject Assembly SRA Nucleotide" --final Master --unique "BioSampleAccession BioSampleAccessionSecondary BioSampleBioProjectAccession"
          NCBImetaExport --database test/test.sqlite --outputdir test/
