#------------------------------------------------------------------------------#
name: Test
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - '.github/workflows/test.yaml*'
      - 'ncbimeta/*'
      - 'test/*'
      - 'requirements.txt'
      - 'setup.py'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  pytest:
    name: PyTest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, "3.10.1"]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip Install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: PyTest Modules
        run: |
          python test/test.py

      - name: Codecov Upload
        if: matrix.python-version == '3.7' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
